env:
  node: true
  commonjs: true
  es6: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
parser: babel-eslint
rules:
    sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: false
      minKeys: 2
plugins:
  - jest